import type { WorkspacePage } from '../types/workspace'

/** 路由清单仅含真实页面，不将未实现的管理后台当作普通入口。 */
export const workspacePages: WorkspacePage[] = [
  {
    name: 'explore',
    path: '/explore',
    title: '发现',
    description: '内容、创作者与实时社区，在这里连接。',
    group: 'space',
    requiresAuth: false,
    section: 'explore',
  },
  {
    name: 'communities',
    path: '/communities',
    title: '社区空间',
    description: '发现公开社区，加入交流，管理你的社区关系。',
    group: 'space',
    requiresAuth: false,
    section: 'communities',
  },
  {
    name: 'creators',
    path: '/creators',
    title: '创作者',
    description: '关注你喜欢的创作者，发现他们的新内容。',
    group: 'space',
    requiresAuth: false,
    section: 'creators',
  },
  {
    name: 'voice',
    path: '/voice',
    title: '语音空间',
    description: '进入真实开放的语音房，或创建自己的讨论空间。',
    group: 'space',
    requiresAuth: false,
    section: 'voice',
  },
  {
    name: 'live',
    path: '/live',
    title: '直播空间',
    description: '发现已确认开播的房间，或为下一次直播建立排期。',
    group: 'space',
    requiresAuth: false,
    section: 'live',
  },
  {
    name: 'studio',
    path: '/studio',
    title: '内容工作台',
    description: '管理草稿、发布内容和维护你的 UP 主主页。',
    group: 'creator',
    requiresAuth: true,
  },
  {
    name: 'assets',
    path: '/assets',
    title: '素材中心',
    description: '管理本人受管图片，按用途上传和复用。',
    group: 'creator',
    requiresAuth: true,
  },
  {
    name: 'voice-owner',
    path: '/studio/voice',
    title: '我的语音房',
    description: '查看本人房间状态并确认关闭，不把媒体请求受理当成成功。',
    group: 'creator',
    requiresAuth: true,
  },
  {
    name: 'messages',
    path: '/messages',
    title: '消息中心',
    description: '私信、群聊、历史检索与消息安全。',
    group: 'collaboration',
    requiresAuth: true,
  },
  {
    name: 'notifications',
    path: '/notifications',
    title: '通知中心',
    description: '读取真实通知，管理已读状态与接收偏好。',
    group: 'collaboration',
    requiresAuth: true,
  },
  {
    name: 'account',
    path: '/account',
    title: '账户与连接',
    description: '查看账户资料、当前会话与可用连接能力。',
    group: 'account',
    requiresAuth: true,
  },
  {
    name: 'operations',
    path: '/operations',
    title: '通知投递运维',
    description: '读取本人真实运营权限，处理通知死信与追加审计。',
    group: 'account',
    requiresAuth: true,
  },
  {
    name: 'binding-operations',
    path: '/operations/binding-releases',
    title: '绑定释放排障',
    description: '按专用权限读取已提交业务的资产保护释放事实与有界状态采样。',
    group: 'account',
    requiresAuth: true,
  },
]

/** 非法路由提供独立找回入口，不能把未知地址误标已命中某个功能。 */
export const unknownPage: WorkspacePage = {
  name: 'not-found',
  path: '',
  title: '页面不存在',
  description: '这个地址不对应已实现的工作台页面。',
  group: 'account',
  requiresAuth: false,
}
